/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#dde3ea',
        outline: '#99907c',
        'surface-bright': '#393939',
        'surface-container': '#1f1f1f',
        surface: '#131313',
        secondary: '#c1c7ce',
        primary: '#f2ca50',
        'surface-container-high': '#2a2a2a',
        'surface-variant': '#353535',
        'surface-container-highest': '#353535',
        'primary-container': '#d4af37',
        'inverse-surface': '#e2e2e2',
        tertiary: '#cfcdd3',
        background: '#131313',
        'primary-fixed-dim': '#e9c349',
        'error-container': '#93000a',
        'surface-container-low': '#1b1b1b',
        'on-secondary-fixed-variant': '#41484d',
        'on-tertiary-fixed': '#1a1b20',
        'surface-dim': '#131313',
        'primary-fixed': '#ffe088',
        'on-tertiary-fixed-variant': '#46464b',
        'on-primary-fixed-variant': '#574500',
        'on-secondary-fixed': '#161c21',
        'inverse-on-surface': '#303030',
        'tertiary-fixed': '#e3e2e8',
        'on-primary-fixed': '#241a00',
        'on-surface-variant': '#d0c5af',
        'on-tertiary-container': '#444549',
        'on-error': '#690005',
        'secondary-fixed-dim': '#c1c7ce',
        error: '#ffb4ab',
        'on-error-container': '#ffdad6',
        'on-secondary': '#2b3136',
        'outline-variant': '#4d4635',
        'on-tertiary': '#2f3035',
        'on-background': '#e2e2e2',
        'surface-container-lowest': '#0e0e0e',
        'tertiary-fixed-dim': '#c7c6cb',
        'on-secondary-container': '#b6bcc3',
        'inverse-primary': '#735c00',
        'on-primary-container': '#554300',
        'surface-tint': '#e9c349',
        'tertiary-container': '#b3b2b8',
        'secondary-container': '#464c52',
        'on-primary': '#3c2f00',
        'on-surface': '#e2e2e2',
        silver: {
          200: '#dde3ea',
          400: '#c1c7ce',
        },
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '32px',
        'container-padding': '64px',
        'section-gap': '128px',
        'element-gap': '16px',
        unit: '8px',
      },
      fontFamily: {
        'label-caps': ['Ubuntu', 'sans-serif'],
        'headline-md': ['"Cinzel Decorative"', 'serif'],
        'body-lg': ['Ubuntu', 'sans-serif'],
        'body-md': ['Ubuntu', 'sans-serif'],
        'headline-lg': ['"Cinzel Decorative"', 'serif'],
        'headline-xl': ['"Cinzel Decorative"', 'serif'],
        cinzel: ['Cinzel', 'serif'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.2em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '0.1em', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0.02em', fontWeight: '300' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0.01em', fontWeight: '300' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '0.15em', fontWeight: '400' }],
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '0.1em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
