/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        thrones: {
          background: '#131313',
          error: '#ffb4ab',
          'error-container': '#93000a',
          'inverse-on-surface': '#303030',
          'inverse-primary': '#735c00',
          'inverse-surface': '#e2e2e2',
          'on-background': '#e2e2e2',
          'on-error': '#690005',
          'on-error-container': '#ffdad6',
          'on-primary': '#3c2f00',
          'on-primary-container': '#554300',
          'on-primary-fixed': '#241a00',
          'on-primary-fixed-variant': '#574500',
          'on-secondary': '#2b3136',
          'on-secondary-container': '#b6bcc3',
          'on-secondary-fixed': '#161c21',
          'on-secondary-fixed-variant': '#41484d',
          'on-surface': '#e2e2e2',
          'on-surface-variant': '#d0c5af',
          'on-tertiary': '#2f3035',
          'on-tertiary-container': '#444549',
          'on-tertiary-fixed': '#1a1b20',
          'on-tertiary-fixed-variant': '#46464b',
          outline: '#99907c',
          'outline-variant': '#4d4635',
          primary: '#f2ca50',
          'primary-container': '#d4af37',
          'primary-fixed': '#ffe088',
          'primary-fixed-dim': '#e9c349',
          secondary: '#c1c7ce',
          'secondary-container': '#464c52',
          'secondary-fixed': '#dde3ea',
          'secondary-fixed-dim': '#c1c7ce',
          surface: '#131313',
          'surface-bright': '#393939',
          'surface-container': '#1f1f1f',
          'surface-container-high': '#2a2a2a',
          'surface-container-highest': '#353535',
          'surface-container-low': '#1b1b1b',
          'surface-container-lowest': '#0e0e0e',
          'surface-dim': '#131313',
          'surface-tint': '#e9c349',
          'surface-variant': '#353535',
          tertiary: '#cfcdd3',
          'tertiary-container': '#b3b2b8',
          'tertiary-fixed': '#e3e2e8',
          'tertiary-fixed-dim': '#c7c6cb',
          brand: {
            neutral: '#000000',
            primary: '#d4af37',
            secondary: '#e0e6ed',
            tertiary: '#0b0c10',
          },
        },
      },
      fontFamily: {
        headline: ['"Cinzel Decorative"', 'serif'],
        body: ['Ubuntu', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
